version: '3'
services:
  node:
    build: ./
    container_name: node
    env_file:
      - ./.env
    ports:
      - 3014:3014
    depends_on:
      - db
    links:
      - db
    networks:
      - mysql-mysql

  db:
    container_name: db
    build: ./database
    ports:
      - 3306:3306
    env_file:
      - ./.env
    networks:
      - mysql-mysql

networks:
  mysql-mysql: