version: '3'
services:
  node:
    build: ./
    env_file:
      - ./.env
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - db
  db:
    build: ./database
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - ./.env